language: java
jdk:
  - openjdk7
  - openjdk6
install: true
script: mvn -q clean install -DobrRepository=false -DHttpTestBase.readyTimeoutSeconds=300 -PwarIntegrationTests -PintegrationTests
notifications:
  email: false
